# GitHub Actions İş Akışı Adı
name: özet

# Bu iş akışının ne zaman çalışacağını belirleyen tetikleyiciler
on:
  # Zamanlanmış görev: Her gün 00:00 UTC'de çalışır (cron sözdizimi)
  schedule:
    - cron: '0 0 * * *'
  # Manuel tetikleme: GitHub Actions sekmesinden elle çalıştırmayı sağlar
  workflow_dispatch:

# İş akışında çalıştırılacak görevler
jobs:
  # "build" adında bir görev tanımlıyoruz
  build:
    # Görevin çalışacağı sanal makine ortamı
    runs-on: ubuntu-latest

    # Görevin adımları
    steps:
      # 1. Adım: Depodaki kodları sanal makineye indirir
      - name: Depoyu Klonla
        uses: actions/checkout@v4

      # 2. Adım: Belirtilen Python sürümünü kurar
      - name: Python'u Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Python sürümünü projenize göre değiştirebilirsiniz

      # 3. Adım: Gerekli Python kütüphanelerini yükler
      - name: Bağımlılıkları Yükle
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements1.txt

      # 4. Adım: Ana Python betiğini çalıştırır
      - name: Betiği Çalıştır
        run: python beinsportsozet.py # Betiğinizin adını doğru yazdığınızdan emin olun

      # 5. Adım: Oluşturulan dosyaları depoya geri yükler (commit ve push)
      - name: Değişiklikleri Depoya Yükle
        run: |
          # Git için kullanıcı adı ve e-posta yapılandırması
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Değişiklikleri sahneye ekle
          git add saku/
          
          # Değişiklik olup olmadığını kontrol et ve varsa commit at
          git diff --staged --quiet || git commit -m "[BOT] M3U Dosyaları Güncellendi"
          
          # Değişiklikleri ana dala (main) gönder
          git push
